Blog/Controllers/AddArController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using System.Data.Entity;
using PagedList.Mvc;
using PagedList;
using Blog.Models;
namespace Blog.Controllers
{
    public class AddArController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: AddAr
        public ActionResult AddAr()
        {
          
            var categories = context.Categories;
            ViewBag.Categories = categories;
            SelectList category = new SelectList(context.Categories, "CategoryId", "CategoryName");
            ViewBag.Category = category;
            //      ViewBag.ProductId = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddAr(Article article)
        {

            context.Articles.Add(article);
            var category = context.Categories;


            context.SaveChanges();
            return RedirectToAction("../Home/");
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BlogYR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Про блог", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакти", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Додати", "AddAr", "AddAr")</li>}
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
      
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>